Update test.yml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -10,7 +10,9 @@ jobs:
     steps:
       - name: validate author
         if: ${{ github.event.comment.author_association }} != "OWNER1"
-        run: echo "::error ${{ github.event.comment.author_association }}::Comment author is not OWNER"
+        run: |
+          echo "::error ${{ github.event.comment.author_association }}::Comment author is not OWNER"
+          exit 1
       - name: set repo name
         run: |
           x=`echo "${{ github.event.comment.body }}" | head -1`
